apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        version: "1.1.41"
    spec:
      serviceAccountName: sa-myapp
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: myapp
        image: ghcr.io/emanuelfds/app:1.1.41
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.2
            memory: 128Mi
          requests:
            cpu: 0.1
            memory: 64Mi
