apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
        version: "1.2.5"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sa-myapp
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: myapp
        image: ghcr.io/emanuelfds/app:1.2.5
        imagePullPolicy: IfNotPresent
        # Descomentar caso queira executar o "stress-ng"
        # securityContext:      
        #     readOnlyRootFilesystem: true
        #     runAsNonRoot: true
        #     runAsUser: 1000
        ports:
        - name: myapp
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5  
          periodSeconds: 30
          failureThreshold: 3
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.1"
            memory: 64Mi
        env:
          - name: APP_CONFIG
            valueFrom:
              configMapKeyRef:
                name: cm-myapp
                key: APP_CONFIG   
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: cm-myapp
                key: LOG_LEVEL
          - name: CPU_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: cm-myapp
                key: CPU_THRESHOLD
          - name: MEMORY_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: cm-myapp
                key: MEMORY_THRESHOLD
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                name: cm-myapp
                key: APP_VERSION
      # tolerations:
      #   - key: "servicesonly"
      #     operator: "Equal"
      #     value: "true"
      #     effect: "PreferNoSchedule"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: apps
      #           operator: In
      #           values:
      #           - services   
            
