apiVersion: v1
kind: Service
metadata:
  name: svc-myapp
  namespace: myapp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.110
    metallb.universe.tf/address-pool: production
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - nodePort: 30002
    port: 80
    targetPort: 5000