apiVersion: v1
kind: Service
metadata:
  name: svc-myapp
  namespace: myapp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.110
    metallb.universe.tf/address-pool: production
spec:
  selector:
    app: myapp
  # type: NodePort
  type: LoadBalancer
  ports:
  # - nodePort: 30002
    - name: app
      port: 80
      targetPort: 5000
      protocol: TCP