apiVersion: v1
kind: Service
metadata:
  name: svc-myapp2
  namespace: myapp2
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.100
    metallb.universe.tf/address-pool: production
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '5000'
spec:
  selector:
    app: myapp2
  type: LoadBalancer
  ports:
    - name: myapp2
      port: 80
      protocol: TCP
      targetPort: 5000