apiVersion: v1
kind: Service
metadata:
  name: svc-myapp
  namespace: myapp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.120
    metallb.universe.tf/address-pool: production
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '5000'
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - name: myapp
      port: 80
      protocol: TCP
      targetPort: 5000