apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        environment: 
        version: 
    spec:
      serviceAccountName: my-app
      containers:
      - name: myapp
        image: emanuelfds/app:v184
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.2
            memory: 128Mi
          requests:
            cpu: 0.1
            memory: 64Mi
